### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remote' of undefined

### ISSUE THREAD

**Issue by ghost** [andrecasal/sftp-upload-on-change#1]
[Enter steps to reproduce:]

1. Hi. Just downloaded ATOM as Dreamweaver Replacement but here's the error code when I want to connect to my FTP

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [sftp-upload-on-change](https://github.com/andrecasal/sftp-upload-on-change) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remote' of undefined

```
At /Users/martin/.atom/packages/sftp-upload-on-change/lib/sftp-upload-on-change.js:223

TypeError: Cannot read property 'remote' of undefined
    at Object.upload (/packages/sftp-upload-on-change/lib/sftp-upload-on-change.js:223:32)
    at /packages/sftp-upload-on-change/lib/sftp-upload-on-change.js:62:12)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/sftp-upload-on-change/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/packages/sftp-upload-on-change/node_modules/chokidar/index.js:241:5)
    at /packages/sftp-upload-on-change/node_modules/chokidar/lib/fsevents-handler.js:206:14)
    at addOrChange (/packages/sftp-upload-on-change/node_modules/chokidar/lib/fsevents-handler.js:212:7)
    at /packages/sftp-upload-on-change/node_modules/chokidar/lib/fsevents-handler.js:218:35
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
  3x -6:21.6.0 core:backspace (input.hidden-input)
     -3:36.6.0 core:cancel (div.package-detail.panels-item)
     -3:21.9.0 remote-ftp:navigate-to (input.hidden-input)
     -3:20.4.0 core:cancel (input.hidden-input)
     -3:16.7.0 remote-ftp:connect (input.hidden-input)
     -1:35 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:30.7.0 core:cancel (input.hidden-input)
     -1:26.3.0 ftp-remote-edit:edit-servers (div.panels-item)
     -1:22 core:confirm (input.hidden-input)
  2x -0:57.1.0 core:backspace (input.hidden-input)
     -0:29.5.0 ftp-remote-edit:toggle (div.panels-item)
     -0:08.0 remote-sync:configure (span.name.icon.icon-file-symlink-directory.icon-file-directory)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.11 
remote-sync 4.1.8 
sftp-upload-on-change 0.1.0 
```

**Comment by andrecasal** [comment]
@mad2kx I believe you opened the sftp-upload-on-change as a project. You're supposed to install it as a Atom plugin instead.

I've added code to prevent reading of .sftp-upload-on-change.json on the sftp-upload-on-change project itself. So now you can open sftp-upload-on-change as a project and it won't show an error for the dummy .sftp-upload-on-change.json file.

Let me know if I helped 👍🏻
