### ISSUE TITLE
Uncaught Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by wenchieh** [andrecasal/sftp-upload-on-change#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: [sftp-upload-on-change](https://github.com/andrecasal/sftp-upload-on-change) package 0.1.0

### Stack Trace

Uncaught Error: All configured authentication methods failed

```
At events.js:183

Error: All configured authentication methods failed
    at tryNextAuth (/packages/sftp-upload-on-change/node_modules/ssh2/lib/client.js:380:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/packages/sftp-upload-on-change/node_modules/ssh2/lib/client.js:591:5)
    at emitTwo (events.js:126:13)
    at SSH2Stream.emit (events.js:214:7)
    at parsePacket (/packages/sftp-upload-on-change/node_modules/ssh2-streams/lib/ssh.js:3929:10)
    at SSH2Stream._transform (/packages/sftp-upload-on-change/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/sftp-upload-on-change/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
  2x -3:03.0 core:save (input.hidden-input)
  3x -2:37.5.0 core:backspace (input.hidden-input)
     -2:31.8.0 core:save (input.hidden-input)
  4x -2:02.0 core:move-down (input.hidden-input)
  3x -2:01.0 core:move-right (input.hidden-input)
 13x -2:00.3.0 core:select-left (input.hidden-input)
 29x -1:58.5.0 core:backspace (input.hidden-input)
     -1:08.4.0 core:paste (input.hidden-input)
  5x -1:04.1.0 core:backspace (input.hidden-input)
     -1:02.5.0 snippets:next-tab-stop (input.hidden-input)
     -1:02.5.0 snippets:expand (input.hidden-input)
     -1:02.5.0 editor:indent (input.hidden-input)
     -1:01.6.0 core:backspace (input.hidden-input)
     -0:56.2.0 core:save (input.hidden-input)
  8x -0:32.2.0 core:backspace (input.hidden-input)
     -0:28 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-python 5.0.0 
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.14.0 
awesome-python-snippets 0.3.0 
better-python-snippets 1.0.0 
docblock-python 0.13.0 
hey-pane 1.1.2 
ide-python 1.4.1 
kite 0.153.0 
language-gnuplot-5 0.4.2 
language-gnuplot-atom 0.2.0 
python-debugger 0.2.0 
python-docstring 0.0.3 
python-isort 0.0.7 
python-line-profiler 0.3.2 
python-requirements 0.2.1 
python-runner 1.2.1 
python-snippets 1.9.0 
python-tools 0.6.9 
run-python-simply 0.6.0 
scroll-through-time 0.3.0 
sftp-upload-on-change 0.1.0 
teletype 0.13.3 
zentabs 0.8.9 
```

**Comment by andrecasal** [comment]
This was an error I was running into and never figured it out. This package is now deprecated because I changed to VS Code.
