### ISSUE TITLE
Uncaught TypeError: Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by egaslan** [andrecasal/sftp-upload-on-change#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [sftp-upload-on-change](https://github.com/andrecasal/sftp-upload-on-change) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'local' of undefined

```
At C:\Users\Elif\.atom\packages\sftp-upload-on-change\lib\sftp-upload-on-change.js:74

TypeError: Cannot read property 'local' of undefined
    at /packages/sftp-upload-on-change/lib/sftp-upload-on-change.js:74:87)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at /packages/sftp-upload-on-change/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/packages/sftp-upload-on-change/node_modules/chokidar/index.js:241:5)
    at /packages/sftp-upload-on-change/node_modules/chokidar/lib/nodefs-handler.js:264:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.32.0 
atom-html-preview 0.2.5 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
browser-plus 0.0.98 
color-picker 2.2.5 
docblockr 0.13.7 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
file-icons 2.1.17 
highlight-selected 0.13.1 
lipsum 0.1.0 
platformio-ide-terminal 2.8.4 
script 3.17.3 
sftp-upload-on-change 0.1.0 
teletype 0.9.0 
youtube-pane 2.0.0 
```

**Comment by andrecasal** [comment]
Fixed in #1
